// frontend/src/components/widgets/widget-recent-prs.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PersonalRecord } from '../../models/stats.model';

@Component({
  selector: 'app-widget-recent-prs',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="bg-light-bg p-6 rounded-2xl border border-secondary shadow-lg overflow-hidden flex flex-col hover:border-primary/50 transition-colors duration-300 h-full">
      <div class="flex justify-between items-center mb-4">
        <p class="text-text-secondary text-[10px] font-bold uppercase tracking-wider">Recordes Recentes</p>
        <span class="text-lg">🏆</span>
      </div>
      
      <div *ngIf="prs.length > 0; else noPrs" class="space-y-3 overflow-y-auto max-h-64 pr-2 custom-scrollbar flex-1">
        <div *ngFor="let pr of prs" class="flex items-center justify-between p-3 rounded-xl bg-secondary/10 hover:bg-secondary/30 transition-colors border border-transparent hover:border-secondary/50 group">
          <div>
            <p class="font-bold text-white text-sm group-hover:text-primary transition-colors truncate max-w-[120px]">{{ pr.exercise_name }}</p>
            <p class="text-[9px] text-text-secondary uppercase mt-0.5 tracking-wide">{{ getFormattedDate(pr.date) }}</p>
          </div>
          <div class="text-right">
            <p class="text-base font-bold text-primary">{{ pr.weight }}<span class="text-xs ml-0.5 font-normal text-primary/70">kg</span></p>
            <div class="flex items-center justify-end text-[9px] text-text-secondary space-x-1">
              <span>{{ pr.reps }} reps</span>
            </div>
          </div>
        </div>
      </div>
      
      <ng-template #noPrs>
        <div class="flex-1 flex flex-col items-center justify-center text-center opacity-60">
          <span class="text-3xl mb-2 grayscale">🏅</span>
          <p class="text-text-secondary text-xs">Sem novos recordes ainda.</p>
          <p class="text-text-secondary text-[10px] mt-1">Continue firme!</p>
        </div>
      </ng-template>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class WidgetRecentPrsComponent {
  @Input({ required: true }) prs: PersonalRecord[] = [];

  getFormattedDate(dateStr: string): string {
    if (!dateStr) return '';
    try {
      const date = new Date(dateStr);
      return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(date);
    } catch {
      return dateStr;
    }
  }
}

// frontend/src/features/dashboard/components/WidgetRecentPRs.tsx
import { Trophy, ArrowUpRight } from 'lucide-react';

import type { PRRecord } from '../../../shared/types/dashboard';

interface WidgetRecentPRsProps {
  prs: PRRecord[];
}

export function WidgetRecentPRs({ prs }: WidgetRecentPRsProps) {
  if (!prs.length) return null;

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 mb-2">
        <Trophy className="text-yellow-500" size={20} />
        <h2 className="text-lg font-bold text-text-primary">Recordes Recentes</h2>
      </div>
      
      <div className="grid gap-3">
        {prs.map((pr) => (
          <div 
            key={pr.id} 
            className="flex items-center justify-between p-4 bg-dark-card border border-border rounded-xl hover:border-yellow-500/30 transition-colors group relative overflow-hidden"
          >
            {/* Background glow effect */}
            <div className="absolute inset-0 bg-gradient-to-r from-yellow-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />

            <div className="flex items-center gap-4 relative z-10">
              <div className="h-10 w-10 rounded-full bg-yellow-500/10 flex items-center justify-center text-yellow-500 font-bold text-xs ring-1 ring-yellow-500/20 group-hover:ring-yellow-500/40 transition-all">
                PR
              </div>
              <div>
                <h4 className="font-bold text-text-primary group-hover:text-yellow-400 transition-colors">{pr.exercise}</h4>
                <p className="text-xs text-text-secondary">
                  {new Date(pr.date).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })} • {pr.reps} reps
                </p>
              </div>
            </div>

            <div className="text-right relative z-10">
              <div className="flex items-center gap-1 justify-end">
                <span className="text-xl font-black text-white tracking-tight">{pr.weight}<span className="text-sm font-medium text-text-muted ml-0.5">kg</span></span>
              </div>
              {pr.previous_weight && (
                 <div className="flex items-center justify-end gap-1 text-xs text-emerald-400 font-medium">
                    <ArrowUpRight size={12} />
                    <span>+{((pr.weight - pr.previous_weight)).toFixed(1)}kg</span>
                 </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
