// frontend/src/features/workouts/components/WorkoutDrawer.tsx
import { X } from 'lucide-react';

import { Button } from '../../../shared/components/ui/Button';
import type { Workout } from '../../../shared/types/workout';
import { cn } from '../../../shared/utils/cn';
import { formatDate } from '../../../shared/utils/format-date';

interface WorkoutDrawerProps {
  workout: Workout | null;
  isOpen: boolean;
  onClose: () => void;
}

/**
 * Drawer component to display workout details with exercises
 * Slides in from the right side of the screen
 */
export function WorkoutDrawer({ workout, isOpen, onClose }: WorkoutDrawerProps) {
  if (!workout) return null;

  return (
    <>
      {/* Backdrop */}
      <div
        className={cn(
          'fixed inset-0 bg-black/60 backdrop-blur-sm z-40 transition-opacity',
          isOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'
        )}
        onClick={onClose}
      />

      {/* Drawer */}
      <div
        className={cn(
          'fixed right-0 top-0 h-full w-full md:w-[500px] bg-dark-card border-l border-border z-50',
          'transform transition-transform duration-300 ease-in-out overflow-y-auto',
          isOpen ? 'translate-x-0' : 'translate-x-full'
        )}
      >
        {/* Header */}
        <div className="sticky top-0 bg-dark-card/95 backdrop-blur-md border-b border-border p-6 flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-text-primary">Detalhes do Treino</h2>
            <p className="text-sm text-text-secondary mt-1">
              {formatDate(workout.date, 'full')}
            </p>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={onClose}
            className="text-text-muted hover:text-text-primary"
          >
            <X size={20} />
          </Button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6">
          {/* Summary */}
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-zinc-900/50 p-4 rounded-xl">
              <p className="text-xs text-text-muted mb-1">Total de Exercícios</p>
              <p className="text-2xl font-bold text-gradient-start">{workout.exercises.length}</p>
            </div>
            <div className="bg-zinc-900/50 p-4 rounded-xl">
              <p className="text-xs text-text-muted mb-1">Duração</p>
              <p className="text-2xl font-bold text-gradient-end">
                {workout.duration_minutes ? `${String(workout.duration_minutes)}min` : 'N/A'}
              </p>
            </div>
          </div>

          {/* Exercises List */}
          <div className="space-y-4">
            <h3 className="text-sm font-semibold text-text-secondary uppercase tracking-wide">
              Exercícios
            </h3>
            
            {workout.exercises.map((exercise, idx) => (
              <div
                key={exercise.exercise_id ?? idx}
                className="bg-zinc-900/30 border border-zinc-800 rounded-xl p-4 space-y-3"
              >
                <div className="flex items-start justify-between">
                  <div>
                    <h4 className="font-semibold text-text-primary">{exercise.exercise_title}</h4>
                    {exercise.notes && (
                      <p className="text-xs text-text-muted mt-1">{exercise.notes}</p>
                    )}
                  </div>
                  <span className="text-xs px-2 py-1 bg-gradient-start/10 text-gradient-start rounded-full">
                    {exercise.sets.length} séries
                  </span>
                </div>

                {/* Sets */}
                <div className="space-y-2">
                  {exercise.sets.map((set, setIdx) => (
                    <div
                      key={setIdx}
                      className="flex items-center justify-between text-sm bg-zinc-900/50 px-3 py-2 rounded-lg"
                    >
                      <span className="text-text-secondary">Série {setIdx + 1}</span>
                      <div className="flex items-center gap-4 text-text-primary">
                        {set.distance_meters != null && (
                          <span className="font-mono text-blue-400">
                            {set.distance_meters}m
                          </span>
                        )}
                        {set.duration_seconds != null && (
                          <span className="font-mono text-cyan-400">
                            {(set.duration_seconds / 60).toFixed(1)}min
                          </span>
                        )}
                        {set.weight_kg != null && set.weight_kg > 0 && (
                          <span className="font-mono">
                            {set.weight_kg}kg
                          </span>
                        )}
                        {set.reps != null && set.reps > 0 && (
                          <span className="font-mono">
                            {set.reps} reps
                          </span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>

                {/* Exercise PRs */}
                {exercise.pr_data && Object.keys(exercise.pr_data).length > 0 && (
                  <div className="pt-2 border-t border-zinc-800">
                    <p className="text-xs text-yellow-500 font-semibold">
                      🏆 PRs: {Object.keys(exercise.pr_data).join(', ')}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Workout Notes */}
          {workout.notes && (
            <div className="bg-blue-500/5 border border-blue-500/20 rounded-xl p-4">
              <h3 className="text-sm font-semibold text-blue-400 mb-2">Anotações</h3>
              <p className="text-sm text-text-primary">{workout.notes}</p>
            </div>
          )}
        </div>
      </div>
    </>
  );
}

// frontend/src/components/workouts/workout-drawer/workout-drawer.component.ts
import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Workout } from '../../../models/workout.model';
import { AppDateFormatPipe } from '../../../pipes/date-format.pipe';

@Component({
  selector: 'app-workout-drawer',
  standalone: true,
  imports: [CommonModule, AppDateFormatPipe],
  templateUrl: './workout-drawer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block' }
})
export class WorkoutDrawerComponent {
  @Input({ required: true }) workout!: Workout;
  @Output() close = new EventEmitter<void>();

  get volumeTotal(): number {
    if (!this.workout?.exercises) return 0;
    return this.workout.exercises.reduce((acc, ex) => {
        const exVol = ex.weights_per_set.reduce((sAcc, w, i) => {
            const r = ex.reps_per_set[i] || 0;
            return sAcc + (w * r);
        }, 0);
        return acc + exVol;
    }, 0);
  }

  get totalSets(): number {
      return this.workout.exercises.reduce((acc, ex) => acc + ex.sets, 0);
  }
}

<div class="fixed inset-0 z-50 flex justify-end" role="dialog" aria-modal="true">
  <!-- Backdrop -->
  <div class="fixed inset-0 bg-black/60 backdrop-blur-sm transition-opacity animate-fade-in" (click)="close.emit()"></div>

  <!-- Drawer Panel -->
  <div class="relative w-full max-w-md bg-dark-bg h-full shadow-2xl flex flex-col transform transition-transform duration-300 ease-in-out border-l border-secondary animate-slide-in-right">
    
    <!-- Header -->
    <div class="p-6 border-b border-secondary flex justify-between items-start bg-light-bg/50">
       <div>
         <div class="flex items-center gap-2">
            <h2 class="text-2xl font-bold text-white tracking-tight">{{ workout.workout_type || 'Treino' }}</h2>
         </div>
         <p class="text-text-secondary text-sm mt-1 flex items-center gap-1">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg>
                    {{ workout.date | appDateFormat:'datetime' }}
         </p>
         <div class="mt-3 text-xs font-mono text-primary bg-primary/10 inline-flex items-center px-2 py-1 rounded border border-primary/20">
            ⏱️ {{ workout.duration_minutes }} min
         </div>
       </div>
       <button (click)="close.emit()" class="text-text-secondary hover:text-white p-2 rounded-full hover:bg-secondary/50 transition-colors">
         <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
           <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
         </svg>
       </button>
    </div>

    <!-- Content: Exercise List -->
    <div class="flex-1 overflow-y-auto p-6 space-y-8 custom-scrollbar">
       <div *ngFor="let ex of workout.exercises" class="space-y-3">
          <div class="flex justify-between items-center px-1">
             <h3 class="text-base font-bold text-white items-center flex gap-2">
                <span class="w-2 h-2 rounded-full bg-primary inline-block"></span>
                {{ ex.name }}
             </h3>
          </div>
          
          <!-- Table -->
          <div class="overflow-hidden rounded-lg border border-secondary shadow-sm">
             <table class="w-full text-sm text-left text-text-secondary">
                <thead class="bg-secondary/20 text-[10px] uppercase text-text-secondary tracking-wider">
                   <tr>
                     <th class="px-4 py-2 font-medium">Série</th>
                     <th class="px-4 py-2 font-medium text-center">Reps</th>
                     <th class="px-4 py-2 font-medium text-right">Peso (kg)</th>
                   </tr>
                </thead>
                <tbody class="divide-y divide-secondary/20 bg-light-bg/20">
                   <tr *ngFor="let reps of ex.reps_per_set; let i = index" class="hover:bg-white/5 transition-colors">
                      <td class="px-4 py-2 font-mono text-xs opacity-70">{{ i + 1 }}</td>
                      <td class="px-4 py-2 text-center text-white font-medium">{{ reps }}</td>
                      <td class="px-4 py-2 text-right font-bold text-primary">
                        {{ ex.weights_per_set[i] ?? '-' }}
                      </td>
                   </tr>
                </tbody>
             </table>
          </div>
       </div>
    </div>

    <!-- Footer -->
    <div class="p-6 border-t border-secondary bg-light-bg/50 backdrop-blur-md">
       <div class="bg-secondary/20 rounded-xl p-4 border border-secondary/50 flex justify-between items-center shadow-inner">
          <div>
            <p class="text-[10px] text-text-secondary uppercase font-bold tracking-wider">Volume Total</p>
            <p class="text-2xl font-bold text-primary mt-0.5">{{ volumeTotal | number:'1.0-0' }} <span class="text-sm font-normal text-text-secondary">kg</span></p>
          </div>
          <div class="text-right">
             <p class="text-[10px] text-text-secondary uppercase font-bold tracking-wider">Total Séries</p>
             <p class="text-2xl font-bold text-white mt-0.5">{{ totalSets }}</p>
          </div>
       </div>
    </div>

  </div>
</div>
