// frontend/src/shared/components/layout/BottomNav.tsx
import {
  LayoutDashboard,
  Dumbbell,
  Utensils,
  User,
  MessageSquare,
  ShieldAlert
} from 'lucide-react';
import { NavLink } from 'react-router-dom';

import { useAuthStore } from '../../hooks/useAuth';

interface NavItemProps {
  to: string;
  icon: React.ReactNode;
  label: string;
  testId: string;
}

interface NavItemProps {
  to: string;
  icon: React.ReactNode;
  label: string;
  testId: string;
  end?: boolean;
}

function NavItem({ to, icon, label, testId, end = false }: NavItemProps) {
  return (
    <NavLink
      to={to}
      end={end}
      data-testid={testId}
      className={({ isActive }) => `
        flex flex-col items-center justify-center flex-1 py-1 px-1 transition-colors duration-200 min-w-0
        ${isActive ? 'text-gradient-start' : 'text-text-secondary hover:text-text-primary'}
      `}
    >
      {icon}
      <span className="text-[8px] md:text-[10px] font-medium mt-0.5 truncate">{label}</span>
    </NavLink>
  );
}

/**
 * BottomNav component for Mobile navigation
 */
export function BottomNav() {
  const { isAdmin } = useAuthStore();

  return (
    <nav className="fixed bottom-0 left-0 right-0 bg-dark-card border-t border-border flex items-center justify-center lg:hidden z-40 safe-area-bottom h-14 md:h-16">
      <div className="flex items-center justify-center w-full h-full">
        <NavItem
          to="/"
          icon={<LayoutDashboard size={20} />}
          label="Home"
          testId="nav-home"
        />
        <NavItem
          to="/workouts"
          icon={<Dumbbell size={20} />}
          label="Treinos"
          testId="nav-workouts"
        />
        <NavItem
          to="/body/nutrition"
          icon={<Utensils size={20} />}
          label="Nutrição"
          testId="nav-nutrition"
        />
        <NavItem
          to="/body"
          icon={<User size={20} />}
          label="Corpo"
          testId="nav-body"
          end={true}
        />
        <NavItem
          to="/chat"
          icon={<MessageSquare size={20} />}
          label="Chat"
          testId="nav-chat"
        />
        {isAdmin && (
          <NavItem
            to="/admin"
            icon={<ShieldAlert size={20} />}
            label="Admin"
            testId="nav-admin"
          />
        )}
      </div>
    </nav>
  );
}

// frontend/src/components/bottom-nav/bottom-nav.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { NavigationService, View } from '../../services/navigation.service';

interface NavItem {
  id: View;
  label: string;
  iconName: string;
  isCenter?: boolean;
}

@Component({
  selector: 'app-bottom-nav',
  templateUrl: './bottom-nav.component.html',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
})
export class BottomNavComponent implements OnInit {
  currentView = this.navigationService.currentView;

  navItems: NavItem[] = [
    { id: 'home', label: 'Home', iconName: 'home' },
    { id: 'workouts', label: 'Treinos', iconName: 'dumbbell' },
    { id: 'coach', label: 'Coach', iconName: 'message-circle', isCenter: true },
    { id: 'body', label: 'Corpo', iconName: 'activity' },
    { id: 'profile', label: 'Perfil', iconName: 'user' },
  ];

  constructor(private navigationService: NavigationService) {}

  ngOnInit(): void {}

  navigate(viewId: View): void {
    this.navigationService.navigateTo(viewId);
  }

  isActive(viewId: string): boolean {
    return this.currentView() === viewId;
  }
}

<nav
  class="fixed bottom-0 left-0 right-0 bg-light-bg border-t border-secondary md:hidden flex justify-around items-center h-16 pb-safe-area"
  data-cy="bottom-nav"
>
  @for (item of navItems; track item.id) {
    <button
      (click)="navigate(item.id)"
      [attr.data-cy]="'nav-' + item.id"
      class="flex flex-col items-center justify-center flex-1 h-full gap-1 transition-colors duration-200"
      [ngClass]="
        isActive(item.id)
          ? item.isCenter
            ? 'bg-gradient-to-r from-primary to-accent text-white'
            : 'text-accent'
          : 'text-text-secondary hover:text-text-primary'
      "
    >
      <lucide-icon [name]="item.iconName" class="w-6 h-6"></lucide-icon>
    </button>
  }
</nav>
