// frontend/src/components/bottom-nav/bottom-nav.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';
import { NavigationService, View } from '../../services/navigation.service';

interface NavItem {
  id: View;
  label: string;
  iconName: string;
  isCenter?: boolean;
}

@Component({
  selector: 'app-bottom-nav',
  templateUrl: './bottom-nav.component.html',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
})
export class BottomNavComponent implements OnInit {
  currentView = this.navigationService.currentView;

  navItems: NavItem[] = [
    { id: 'home', label: 'Home', iconName: 'home' },
    { id: 'workouts', label: 'Treinos', iconName: 'dumbbell' },
    { id: 'coach', label: 'Coach', iconName: 'message-circle', isCenter: true },
    { id: 'body', label: 'Corpo', iconName: 'activity' },
    { id: 'profile', label: 'Perfil', iconName: 'user' },
  ];

  constructor(private navigationService: NavigationService) {}

  ngOnInit(): void {}

  navigate(viewId: View): void {
    this.navigationService.navigateTo(viewId);
  }

  isActive(viewId: string): boolean {
    return this.currentView() === viewId;
  }
}

<nav
  class="fixed bottom-0 left-0 right-0 bg-light-bg border-t border-secondary md:hidden flex justify-around items-center h-16 pb-safe-area"
  data-cy="bottom-nav"
>
  @for (item of navItems; track item.id) {
    <button
      (click)="navigate(item.id)"
      [attr.data-cy]="'nav-' + item.id"
      class="flex flex-col items-center justify-center flex-1 h-full gap-1 transition-colors duration-200"
      [ngClass]="
        isActive(item.id)
          ? item.isCenter
            ? 'bg-gradient-to-r from-primary to-accent text-white'
            : 'text-accent'
          : 'text-text-secondary hover:text-text-primary'
      "
    >
      <lucide-icon [name]="item.iconName" class="w-6 h-6"></lucide-icon>
    </button>
  }
</nav>

// frontend-react/src/shared/components/layout/BottomNav.tsx
import { 
  LayoutDashboard, 
  Dumbbell, 
  Utensils, 
  User, 
  MessageSquare
} from 'lucide-react';
import { NavLink } from 'react-router-dom';

interface NavItemProps {
  to: string;
  icon: React.ReactNode;
  label: string;
  testId: string;
}

function NavItem({ to, icon, label, testId }: NavItemProps) {
  return (
    <NavLink
      to={to}
      data-testid={testId}
      className={({ isActive }) => `
        flex flex-col items-center justify-center flex-1 py-2 transition-colors duration-200
        ${isActive ? 'text-gradient-start' : 'text-text-secondary hover:text-text-primary'}
      `}
    >
      {icon}
      <span className="text-[10px] font-medium mt-1">{label}</span>
    </NavLink>
  );
}

/**
 * BottomNav component for Mobile navigation
 */
export function BottomNav() {
  return (
    <nav className="fixed bottom-0 left-0 right-0 h-16 bg-dark-card border-t border-border flex items-center lg:hidden z-40 safe-area-bottom">
      <NavItem 
        to="/" 
        icon={<LayoutDashboard size={22} />} 
        label="Home" 
        testId="nav-home" 
      />
      <NavItem 
        to="/workouts" 
        icon={<Dumbbell size={22} />} 
        label="Treinos" 
        testId="nav-workouts" 
      />
      <NavItem 
        to="/nutrition" 
        icon={<Utensils size={22} />} 
        label="Nutrição" 
        testId="nav-nutrition" 
      />
      <NavItem 
        to="/body" 
        icon={<User size={22} />} 
        label="Corpo" 
        testId="nav-body" 
      />
      <NavItem 
        to="/chat" 
        icon={<MessageSquare size={22} />} 
        label="Chat" 
        testId="nav-chat" 
      />
    </nav>
  );
}
