// frontend/src/shared/components/ui/ConfirmationModal.tsx
import { AlertTriangle, Info } from 'lucide-react';

import { type ConfirmationOptions } from '../../hooks/useConfirmation';
import { cn } from '../../utils/cn';

interface ConfirmationModalProps {
  isOpen: boolean;
  options: ConfirmationOptions;
  onAccept: () => void;
  onCancel: () => void;
}

/**
 * Confirmation modal component
 *
 * Displays a modal dialog for confirming actions.
 * Supports multiple variants (danger, primary) and custom content.
 */
export function ConfirmationModal({
  isOpen,
  options,
  onAccept,
  onCancel,
}: ConfirmationModalProps) {
  if (!isOpen) {
    return null;
  }

  const isDanger = options.type === 'danger';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
      {/* Backdrop */}
      <div
        data-testid="modal-backdrop"
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onCancel}
      />

      {/* Modal */}
      <div
        data-testid="confirmation-modal"
        className="relative bg-dark-card border border-border rounded-2xl p-6 max-w-md w-full shadow-2xl animate-in zoom-in-95 duration-200"
      >
        {/* Icon & Title */}
        <div className="flex flex-col items-center text-center mb-6">
          <div className={cn(
            "w-12 h-12 rounded-full flex items-center justify-center mb-4",
            isDanger ? "bg-red-500/10 text-red-500" : "bg-gradient-start/10 text-gradient-start"
          )}>
            {isDanger ? <AlertTriangle size={24} /> : <Info size={24} />}
          </div>
          <h3 className="text-xl font-bold text-text-primary">
            {options.title ?? 'Confirmar Ação'}
          </h3>
        </div>

        {/* Message */}
        <p className="text-center text-text-secondary mb-8">
          {options.message}
        </p>

        {/* Buttons */}
        <div className="flex gap-3">
          <button
            data-testid="confirm-cancel"
            onClick={onCancel}
            className="flex-1 h-11 px-4 rounded-xl bg-dark-bg border border-border text-text-primary font-medium hover:bg-white/5 transition-all active:scale-95"
          >
            {options.cancelText ?? 'Cancelar'}
          </button>
          <button
            data-testid="confirm-accept"
            onClick={onAccept}
            className={cn(
              "flex-1 h-11 px-4 rounded-xl text-white font-bold transition-all active:scale-95 shadow-lg",
              isDanger 
                ? "bg-red-500 hover:bg-red-600 shadow-red-500/20" 
                : "bg-gradient-to-r from-gradient-start to-gradient-end hover:opacity-90 shadow-orange"
            )}
          >
            {options.confirmText ?? 'Confirmar'}
          </button>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/shared/confirmation-modal/confirmation-modal.component.ts
import { Component, inject } from '@angular/core';
import { ConfirmationService } from '../../../services/confirmation.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-confirmation-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (confirmationService.isVisible()) {
      <div class="fixed inset-0 z-[9999] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
        <div class="bg-light-bg rounded-2xl border border-secondary shadow-2xl max-w-md w-full p-6 space-y-4 animate-in fade-in zoom-in duration-200">
          <h3 class="text-xl font-bold text-text-primary">
            {{ confirmationService.config()?.title || 'Confirmar' }}
          </h3>
          <p class="text-text-secondary">
            {{ confirmationService.config()?.message }}
          </p>
          <div class="flex gap-3">
            <button
              (click)="confirmationService.onCancel()"
              class="flex-1 px-4 py-2 rounded-lg bg-secondary hover:bg-secondary/80 text-white transition-colors">
              {{ confirmationService.config()?.cancelText || 'Cancelar' }}
            </button>
            <button
              (click)="confirmationService.onConfirm()"
              class="flex-1 px-4 py-2 rounded-lg bg-primary hover:bg-primary/80 text-white transition-colors">
              {{ confirmationService.config()?.confirmText || 'Confirmar' }}
            </button>
          </div>
        </div>
      </div>
    }
  `
})
export class ConfirmationModalComponent {
  confirmationService = inject(ConfirmationService);
}
